# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - comms-test

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'comms-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c8b2fe1542b4afa88e78d2632d6bf28 }}
        package: ${{env.DOTNET_ROOT}}/myapp
        app_location: "/" # App source code path
        api_location: "api" # Api source code path - optional
        app_artifact_location: "public" # Built app content directory - optional